title: bump-build-number
image: codefreshplugins/bump-build-number
categories:
  - build
version: 0.2.0
description: Bump the current pipeline's build number
keywords:
  - build
sources:
  - https://github.com/codefresh-contrib/azure-build
maintainers:
  - name: Brandon Phillips
    email: brandon@codefresh.io
icon: https://raw.githubusercontent.com/codefresh-plugins/bump-build-number/master/icon.png
envs:
  - name: ANNOTATION_NAME
    type: optional
    description: Can overwrite the default annotation name of build_number